apiVersion: v1
kind: Service
metadata:
  name: logger
  namespace: fel-service
  labels:
    app: logger
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "3000"
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    app: logger
