apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: promtail-sa
    namespace: fel-service
roleRef:
  kind: ClusterRole
  name: promtail-cluster-role
  apiGroup: rbac.authorization.k8s.io